name: photo_gallery
description: Photo Gallery App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.0.0
  awesome_dio_interceptor: ^1.3.0
  bloc: ^8.1.4
  build_runner: ^2.4.14
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
